#!/bin/bash

#$ -cwd
# error = Merged with joblog
#$ -o joblog.$JOB_ID
#$ -j y
## Edit the line below as needed:
#$ -l h_rt=20:00:00,h_data=50G,gpu,A100,gpu_mem=35G,cuda=1    #RTX2080Ti V100  A100 #100G 
## Modify the parallel environment
## and the number of cores as needed:
#$ -pe shared 1
# Notify when
#$ -m a
# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load anaconda3
conda activate base
conda activate tf_A100_clean


# echo job info on joblog:
echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "

#set file paths
model_name='GRL_multiclass'

mmap_neutral='/u/home/b/baeria/project-ngarud/GHISTBrendan/ProcessingData/neutrals.npy' # neutral processed simulations
mmap_sweep='/u/home/b/baeria/project-ngarud/GHISTBrendan/ProcessingData/sweeps.npy' # sweep processed simulations
mmap_target='/u/project/ngarud/Garud_lab/aDNA/TrainingData/target_N-H_ALL_RowFreq_n150_w201.npy' # processed GHIST dataset ####### NOT SET PROPERLY YET ###########


nvidia-smi --query-gpu=utilization.gpu,memory.used,memory.total --format=csv -l 60 > gpu_usage.log &

#run code
python main_train.py model_name mmap_neutral mmap_sweep mmap_target ##### NOT SET PROPERLY YET #####

# echo job info on joblog:
echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "